name: Push to wp-gatsby-gutenberg
on: push
# on:
#     push:
#         tags:
#             - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: publish:wp-gatsby-gutenberg
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:GatsbyWPGutenberg/wp-gatsby-gutenberg.git
          BRANCH: master
          FOLDER: plugins/wp-gatsby-gutenberg
          SSH_PRIVATE_KEY: ${{ secrets.WP_GATSBY_GUTENBERG_PRIVATE_KEY }}
